core-welcome:
    path:       /welcome
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\Login::welcome' }
core-account-disco-clearchoices:
    path:       /account/disco/clearchoices
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\Login::cleardiscochoices' }
core-loginuserpass:
    path:       /loginuserpass
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\Login::loginuserpass' }
core-loginuserpassorg:
    path:       /loginuserpassorg
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\Login::loginuserpassorg' }
core-error-nocookie:
    path:       /error/nocookie
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\Exception::nocookie' }
core-cardinality:
    path:       /error/cardinality
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\Exception::cardinality' }
core-warning-shortssointerval:
    path:       /warning/short_sso_interval
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\Exception::shortSsoInterval' }
core-post-redirect:
    path:       /postredirect
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\Redirection::postredirect' }
core-logout:
    path:       /logout/{as}
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\Logout::logout' }
core-logout-resume:
    path:       /logout-resume
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\Logout::resumeLogout' }
core-logout-iframe:
    path:       /logout-iframe
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\Logout::logoutIframe' }
core-logout-iframe-done:
    path:       /logout-iframe-done
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\Logout::logoutIframeDone' }
core-logout-iframe-post:
    path:       /logout-iframe-post
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\Logout::logoutIframePost' }
core-error-report:
    path:       /errorReport
    defaults:   { _controller: '\SimpleSAML\Module\core\Controller\ErrorReport::main' }
